name: Daily Commit

on:
  schedule:
    - cron: "27 16 * * *" # Runs daily at 02:30 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Configure Git (aditya.dandriyal@gramener.com)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "aditya.dandriyal@gramener.com"

      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://AdityaDandriyal:${PAT_TOKEN}@github.com/AdityaDandriyal/new.git
          git add last_run.txt
          git commit -m "Automated commit - $(date)" || echo "No changes to commit"
          git push origin main

